# Generated by Django 4.0.4 on 2022-10-12 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=254)),
                ('googgle_map', models.ImageField(upload_to='photos/google_map/Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='photos/logos')),
                ('google_map', models.ImageField(upload_to='', verbose_name='photos/google_map/Bussiness')),
                ('dealing_type', models.TextField(choices=[('entertainment', 'entertainment'), ('technician', 'technician'), ('selling', 'selling'), ('event planners', 'event planners'), ('hair dressers', 'hair dressers'), ('other', 'other')], max_length=30)),
                ('dealings', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=30)),
                ('other_info', models.TextField(max_length=200, null=True)),
                ('liscences', models.ImageField(null=True, upload_to='photos/liscences')),
                ('phone_number', models.CharField(max_length=10)),
                ('images', models.FileField(upload_to='photo/bussiness')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('google_map', models.ImageField(null=True, upload_to='photos/google_map/customer')),
                ('county', models.TextField(max_length=30)),
                ('sub_county', models.TextField(max_length=30, null=True)),
                ('local_town', models.TextField(max_length=30, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='photos/profiles')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(null=True, upload_to='photos/logos')),
                ('google_map', models.ImageField(upload_to='', verbose_name='photos/google_map/Bussiness')),
                ('dealing_type', models.TextField(choices=[('entertainment', 'entertainment'), ('technicians', 'technicians'), ('selling', 'selling'), ('event planners', 'dormant'), ('hair dressers', 'hair dressers')], max_length=30)),
                ('dealings', models.TextField(max_length=1000)),
                ('location', models.TextField(max_length=30)),
                ('other_info', models.TextField(max_length=200, null=True)),
                ('liscences', models.ImageField(null=True, upload_to='photos/liscences')),
                ('email', models.EmailField(max_length=154)),
                ('phone_number', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='photos/bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(null=True)),
                ('images', models.FileField(upload_to='photo/bussiness')),
                ('video', models.FileField(upload_to='videos')),
                ('description', models.TextField(max_length=200)),
                ('mode_of_delivery', models.TextField(max_length=50)),
                ('operation_time', models.DateField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('to', models.TextField(max_length=50)),
                ('category', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('images', models.FileField(upload_to='photo/bussiness')),
                ('video', models.FileField(upload_to='videos')),
                ('description', models.TextField(max_length=200)),
                ('mode_of_delivery', models.TextField(max_length=50)),
                ('operation_time', models.DateField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='TestimoniesExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.TextField(max_length=200)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.expertise')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TestimoniesBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimony', models.TextField(max_length=200)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='StateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.service')),
            ],
        ),
        migrations.CreateModel(
            name='ReferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.merchandise')),
                ('refered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReferExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=30)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.expertise')),
                ('refered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReferBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee', models.CharField(max_length=30)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
                ('refered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RatingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='RatingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='RatingExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='RatingBussiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=200)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='NewsReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reads', models.PositiveIntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.news')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.TextField(max_length=200)),
                ('bussiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('neccesary_info', models.TextField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('google_map', models.ImageField(upload_to='photos/google_maps/events')),
                ('category', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('visits', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(max_length=30)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.bussiness')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('duration', models.DurationField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.merchandise')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.service')),
            ],
        ),
    ]
