# Generated by Django 4.0.4 on 2022-10-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMerchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('merchendise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.merchandise')),
            ],
        ),
    ]
