# Generated by Django 4.0.4 on 2022-10-12 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_statemerchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountMerchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('duration', models.DurationField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('duration', models.DurationField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.service')),
            ],
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='name',
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
