# Generated by Django 4.0.4 on 2022-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_discountmerchandise_discountservice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimoniesexpert',
            old_name='bussiness',
            new_name='expert',
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='dealing_type',
            field=models.TextField(choices=[('entertainment', 'entertainment'), ('technician', 'technician'), ('selling', 'selling'), ('news', 'news'), ('event planners', 'event planners'), ('hair dressers', 'hair dressers'), ('other', 'other')], max_length=30),
        ),
    ]
