# Generated by Django 4.0.4 on 2022-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_rename_bussiness_testimoniesexpert_expert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='google_map',
            field=models.URLField(),
        ),
    ]
