# Generated by Django 4.0.4 on 2022-10-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_events_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='google_map',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='google_map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='google_map',
            field=models.URLField(),
        ),
    ]
