# Generated by Django 4.0.4 on 2022-10-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_bussiness_google_map_alter_customer_google_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(max_length=15),
        ),
    ]
