# Generated by Django 4.0.4 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_customer_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='local_town',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sub_county',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
