# Generated by Django 4.0.4 on 2022-10-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='location',
        ),
        migrations.AddField(
            model_name='expertise',
            name='county',
            field=models.TextField(default='meru', max_length=15),
        ),
        migrations.AddField(
            model_name='expertise',
            name='local_town',
            field=models.CharField(default='nchiru', max_length=15),
        ),
        migrations.AddField(
            model_name='expertise',
            name='sub_county',
            field=models.CharField(default='nchiru', max_length=15),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='liscences',
            field=models.ImageField(blank=True, null=True, upload_to='photos/liscences'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='other_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/bussiness'),
        ),
    ]
