# Generated by Django 4.0.4 on 2022-10-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_remove_expertise_location_expertise_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='county',
            field=models.CharField(default='meru', max_length=15),
        ),
    ]
