# Generated by Django 4.0.4 on 2022-10-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
