# Generated by Django 4.0.4 on 2022-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='brand_name',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='brand_name',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='expertise',
            name='brand_name',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
