# Generated by Django 4.0.4 on 2022-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_bussiness_brand_name_customer_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='dealing_type',
        ),
        migrations.AddField(
            model_name='bussiness',
            name='dealing_list',
            field=models.CharField(default='selling', max_length=50),
        ),
    ]
