# Generated by Django 4.0.4 on 2022-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_rename_operation_time_merchandise_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='referbussiness',
            name='message',
            field=models.TextField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='referexpert',
            name='message',
            field=models.TextField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='referproduct',
            name='message',
            field=models.TextField(default='none', max_length=50),
        ),
    ]
