# Generated by Django 4.0.4 on 2022-10-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_referbussiness_message_referexpert_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='to',
        ),
        migrations.AddField(
            model_name='news',
            name='message',
            field=models.TextField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
