# Generated by Django 4.0.4 on 2022-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_remove_news_to_news_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsreads',
            name='likes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
