# Generated by Django 4.0.4 on 2022-10-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_alter_ratingproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='visits',
        ),
    ]
