# Generated by Django 4.0.4 on 2022-10-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_remove_events_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='location',
        ),
        migrations.AddField(
            model_name='bussiness',
            name='county',
            field=models.CharField(default='meru', max_length=15),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='local_town',
            field=models.CharField(default='nchiru', max_length=15),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='sub_county',
            field=models.CharField(default='nchiru', max_length=15),
        ),
    ]
