# Generated by Django 4.0.4 on 2022-10-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_alter_bussiness_dealings_alter_bussiness_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='liscences',
            field=models.ImageField(blank=True, null=True, upload_to='photos/liscences'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/logos'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='other_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
