# Generated by Django 4.0.4 on 2022-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_alter_bussiness_liscences_alter_bussiness_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='photo/bussiness'),
        ),
    ]
